version: '3.8'

services:
    fcc-app:
        image: freecodecamp-chengdu/fcc:latest
        container_name: fcc-chengdu
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./caddy_data:/data
            - ./caddy_config:/config
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
        environment:
            - TZ=Asia/Shanghai # 设置时区，根据需要
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost'
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
